package com.tqs.homework;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestTemplate;

@CrossOrigin
@Controller    // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class ForecastController {
    private static final Logger log = LoggerFactory.getLogger(ForecastController.class);

    private RestTemplate restTemplate = new RestTemplate();

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ForecastRepository forecastRepository;
    @Autowired
    private DailyRepository dailyRepository;
    @Autowired
    private DataRepository dataRepository;

    /*@GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewForecast (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Forecast n = new Forecast();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }*/

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Forecast> getAllForecasts() {
        // This returns a JSON or XML with the users
        return forecastRepository.findAll();
    }


    @GetMapping(path="/forecast")
    public @ResponseBody Forecast getForecast(@RequestParam double latitude, @RequestParam double longitude) {
        if (forecastRepository.existsByLatitudeAndLongitude(latitude, longitude)) {
            Forecast forecast = forecastRepository.findByLatitudeAndLongitude(latitude,longitude);
            log.info(forecast.toString());
            return forecast;
        } else {
            Forecast forecast = restTemplate.getForObject(
                    "https://api.darksky.net/forecast/21555dff0ae2af8abca7aa189973ef7a/" + latitude + "," + longitude, Forecast.class);

            for (Data d : forecast.getDaily().getData())
                dataRepository.save(d);
            dailyRepository.save(forecast.getDaily());
            forecastRepository.save(forecast);
            log.info(forecast.toString());
            return forecast;
        }
    }
}
